{
 "title": "Apartment Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht22_temperature_celsius" }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dht22_humidity" }
   ]
  },
  {
   "title": "Current Temperature (MH_Z19)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mh_z19_raw_temperature_celsius-48"
    }
   ]
  },
  {
   "title": "CO2 (MH_Z19)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mh_z19_co2" }
   ]
  },
  {
   "title": "Temperature (DHT22)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    { "expr": "dht22_temperature_celsius" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "humidity", "label": "Humidity" }
   ],
   "targets": [
    { "expr": "dht22_humidity" }
   ]
  },
  {
   "title": "CO2 (MH_Z19)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ppm", "label": "Temperature" }
   ],
   "targets": [
    { "expr": "mh_z19_co2" }
   ]
  },
  {
   "title": "Temperature (MH_Z19)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "mh_z19_raw_temperature_celsius-48"
    }
   ]
  },
  {
   "title": "Unnamed  (MH_Z19)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none", "label": "UhUl" }
   ],
   "targets": [
    { "expr": "mh_z19_unnamed" }
   ]
  }
 ]
}